[package]
name = "emulsion"
version = "1.3.0"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]
edition = "2018"
build = "build.rs"

[workspace]
members = [
    "subcrates/gelatin",
]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
gelatin = { path = "./subcrates/gelatin" }
sys-info = "=0.5.8"
error-chain = "0.12"
backtrace = "0.3"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.13"
rand = "0.5"
alphanumeric-sort = "1.0"
trash = "1.0"
