[package]
name = "emulsion"
version = "1.10.0"
description = "A fast and minimalistic image viewer"
repository = "https://github.com/ArturKovacs/emulsion"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]
license = "MIT"
readme = "README.md"
edition = "2018"
build = "build.rs"

[workspace]
members = [
    "subcrates/gelatin",
]

[features]
default = ["networking"]
networking = ["reqwest"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
gelatin = { path = "./subcrates/gelatin" }
reqwest = { version = "0.10", features = ["json", "blocking"], optional = true }
open = "1.4.0"
sys-info = "=0.5.8"
error-chain = "0.12"
backtrace = "0.3"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
rand = "0.7"
alphanumeric-sort = "1.0"
trash = "1.0"
