[package]
name = "emulsion"
version = "0.1.0"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]

[dependencies]
glium = "0.20"
glutin = "0.13"
image = "0.18"
cgmath = "0.16"
error-chain = "0.11"
sys-info = "0.5"
