[package]
name = "emulsion"
version = "2.0.0"
description = "A fast and minimalistic image viewer"
repository = "https://github.com/ArturKovacs/emulsion"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]
license = "MIT"
readme = "README.md"
edition = "2018"
build = "build.rs"

[workspace]
members = [
    "subcrates/gelatin",
]

[profile.dev.package."*"]
opt-level = 1
[profile.dev.build-override]
opt-level = 1
[profile.release]
lto = true

[features]
default = []
networking = ["ureq", "serde_json"]

[package.metadata.bundle]
name = "Emulsion"
identifier = "io.github.arturkovacs.emulsion"
icon = ["resource_dev/emulsion.png"]
resources = ["LICENSE.txt"]
short_description = "A lightweight and minimalistic image viewer"
copyright = "Copyright (c) 2020 The Emulsion Contributors"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
#gelatin = { path = "./subcrates/gelatin" }
gelatin = "0.3"
ureq = { version = "0.12", features = ["json"], optional = true }
lazy_static = "1.4.0"
directories = "2.0.2"
open = "1.4.0"
sys-info = "=0.5.8"
error-chain = "0.12"
backtrace = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
toml = "0.5"
rand = "0.7"
alphanumeric-sort = "1.0"
trash = "1.0"
clap = { version = "2.33", default-features = false }
