[package]
name = "emulsion"
version = "0.1.0"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]
build = "build.rs"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
glium = "0.22"
image = "0.19"
cgmath = "0.16"
error-chain = "0.12"
sys-info = "0.5"
backtrace = "0.3"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = "0.13"
rand = "0.5"

[dependencies.glutin]
version = "0.17"
features = [
    "icon_loading"
]
