[package]
name = "emulsion"
version = "0.1.0"
authors = ["Artur Barnabas <kovacs.artur.barnabas@gmail.com>"]

[dependencies]
#glium = "0.20"
glium = "0.22"
#glutin = "0.13"
glutin = "0.17"
image = "0.19"
cgmath = "0.16"
error-chain = "0.12"
sys-info = "0.5"
