[package]
name = "gelatin"
version = "0.1.0"
authors = ["Artur Kovacs <kovacs.artur.barnabas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.17"
image = "0.23.0"

[dependencies.glium]
version = "0.26"
features = [
#    "icon_loading"
]
